#ifndef __CERTS_H_
#define __CERTS_H_

#include <Arduino.h>

const char ca_pem[] = R"(-----BEGIN CERTIFICATE-----
MIICDTCCAbOgAwIBAgIUFQ+5k7cXxd3IbjSlg74XLmU2Q9gwCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGElu
dGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEVMBMGA1UEAwwMMTkyLjE2OC4xLjc0MB4X
DTI1MDcyODA3MzIzOFoXDTI2MDcyODA3MzIzOFowXDELMAkGA1UEBhMCQVUxEzAR
BgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5
IEx0ZDEVMBMGA1UEAwwMMTkyLjE2OC4xLjc0MFkwEwYHKoZIzj0CAQYIKoZIzj0D
AQcDQgAE6ON+9ikxtJGm5ptReLnm0KA3fo2j7eYmAb2RSq/acllG2wmkHZd6JF8E
2cB6fG+T8clhM3ESLtAyjaIhEV8Wy6NTMFEwHQYDVR0OBBYEFFD8IDSTclPcB7Pu
TFzcU3w23vdVMB8GA1UdIwQYMBaAFFD8IDSTclPcB7PuTFzcU3w23vdVMA8GA1Ud
EwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIgL6US3EaWZ6o7prdO/e2a3XEt
Nf/6PjGAk9XLQZdXyJcCIQChcmQVLl2B8UV8FNjsKh5KVdZBOw1/aO8cq6S3ib8Y
2g==
-----END CERTIFICATE-----
)";

const char key_pem[] = R"(-------BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIHQPo6r4ScZ6n5Gex7vVry/8+j1FNMOWOPji2srwUhIsoAoGCCqGSM49
AwEHoUQDQgAE6bYul/FrV+ig+VNsc/FLQSItkZgO46PbYcrOJEly4DAyk74pdYVH
mk/QbJ9oNF9sEudQ+avyuRZq1klaFwjyrg==
-----END EC PRIVATE KEY-----
)";

const char cert_pem[] = R"(-----BEGIN CERTIFICATE-----
MIICDjCCAbOgAwIBAgIUOqfp2w2Bdjg2tgNTPr7AjlHbXrIwCgYIKoZIzj0EAwIw
XDELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGElu
dGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEVMBMGA1UEAwwMdGVzdC1kZXZpY2UxMB4X
DTI1MDcyODA3NDAwN1oXDTI2MDcyODA3NDAwN1owXDELMAkGA1UEBhMCQVUxEzAR
BgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5
IEx0ZDEVMBMGA1UEAwwMdGVzdC1kZXZpY2UxMFkwEwYHKoZIzj0CAQYIKoZIzj0D
AQcDQgAE6bYul/FrV+ig+VNsc/FLQSItkZgO46PbYcrOJEly4DAyk74pdYVHmk/Q
bJ9oNF9sEudQ+avyuRZq1klaFwjyrqNTMFEwHQYDVR0OBBYEFFSCde7UBAdihCEL
VVSZziVveh5SMB8GA1UdIwQYMBaAFFSCde7UBAdihCELVVSZziVveh5SMA8GA1Ud
EwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhAOkKb8K3beTLOAvmlDFADIAC
BkwzCuqHCeGCEHTI6XC8AiEAgNBM7b+3ABTgJQpImUqfcGLsLe7+0U5vSlywDHkx
n4c=
-----END CERTIFICATE-----
)";

#endif